all: p1 p2 p3 p4-execl p4-execle p4-execlp p4-execv p4-execvp

clean:
	rm -f p1 p2 p3 p4-execl p4-execle p4-execlp p4-execv p4-execvp

p1: p1.c
	gcc -o p1 p1.c -Wall

p2: p2.c
	gcc -o p2 p2.c -Wall

p3: p3.c
	gcc -o p3 p3.c -Wall

p4-execl: p4-execl.c
	gcc -o p4-execl p4-execl.c -Wall

p4-execle: p4-execle.c
	gcc -o p4-execle p4-execle.c -Wall

p4-execlp: p4-execlp.c
	gcc -o p4-execlp p4-execlp.c -Wall

p4-execv: p4-execv.c
	gcc -o p4-execv p4-execv.c -Wall

p4-execvp: p4-execvp.c
	gcc -o p4-execvp p4-execvp.c -Wall